export const postsArray = [

    {
        title : "Starting the Process",
        content : "It all has to start somewhere. In 2021, I had a job running a snack foods route (chips, popcorn, pretzels, dip). After I got off, my routine was to go home, spend time with my girlfriend, spend time with my dog and play whatever video game was holding my attention (at this time I was really into Destiny 2), spend time with a friend every other week or month, and (at a VERY distant last) look for a new job that would hopefully turn into a career. I had been at my job for only 2 years, but it had a lot of problems, taxes and health insurance were not included. <br>While playing games, I'd usually watch YouTube or netflix on another screen, to keep my brain occupied during loading or if I just got bored of what my attention should be focused on. I had been looking into careers that payed 100k without a degree, while I had attended college classes via running start in high school I was never the most driven student, but I had been having a desire for more. In my recommendations I saw a video from the channel 'Dorian Develops'; the title, 'High School DROPOUT to SELF-TAUGHT Programmer In My 30s with a GED! (No Degree) [My Success Story]', is probably one the most YouTubiest titles to ever be on that platform. But damn did it get me excited. I had messed around with some jail breaking with my childhood PSP (you'll never get me Sony, we were GODS with those emulators), and am usually first to be called when any of my immediate family is experiencing a tech emergency, and hell I taught myself how to build my own computer by just watching a few videos, so how hard can be to learn how to create a website, not just by using a service to help me, but really understanding and creating it from scratch? I started on the journey to find out. I'm still on that journey, but I've come a very long way. From freeCodeCamps Responsive Web Design Certificate, to working through Scrimba's Front End Wev Developer Career path, every day is a new journey into something new and exciting. Learning the DOM, how one coding language can feed into other code and the pointers to other ",
        uuid: crypto.randomUUID()
    },
    {
        title : 'Waymond\'s\ EEAAO Speech, Cinema that Makes Me Cry',
        content : "I just talked to her<br> You think im weak don't you. all of those years ago when we first fell in love you're father would say I was too sweet for my own good... maybe he was right<br> Please can we just stop fighting?<br> You tell me it's a cruel world. and we're all just running around in circles... I know that. I've been on this earth just as many days as you. <br> I know you're all fighting because you're scared and confused. Im confused too. all day, I don't know what the heck is going on but somehow all of this feels like it's my fault.<br> When I chose to see the good side of things, I'm not being naive. It is strategic and necessary. It's how I've learned to survive through everything.<br> I don't know, the only thing I do know.. Is that we have to be kind, please be kind... Especially when we don't know what's going on. <br> I know you see yourself as a fighter. Well, I see myself as one too... This is how I fight.",
        uuid: crypto.randomUUID()
    }

]